### ISSUE TITLE
randomize expiry headers through a duration

### ISSUE THREAD

**Issue by paultag** [openstates/indiana-docs#2]
I'd like to trick Varnish into staggering the cache, here's my proposed approach
- Hash the incoming path with SHA1/256. Doesn't need to be secure, just fast.
- Run that hash through a modulo on the duration length. 7*24 seems like a good start.
- Add the duration number to the monday of that week.
- If the duration is in the past, add it to next week.
- Serve that out as the Experation header

This could, of course, all be a moot point if we end up being able to handle the load as-is. Just writing this up as a todo.

Thoughts?

**Comment by paultag** [comment]
cc @timball

**Comment by rshorey** [comment]
We've discussed keeping this on the backburner until anything actually becomes a problem. No problems yet.

**Comment by jamesturk** [comment]
seeing as it has been ~2 years w/o a problem, going to assume we're fine on this.  robots aren't indexing this (by design) so the load is pretty low and unlikely to increase
